-- Per-language content overrides. Base text columns stay the default (ru);
-- i18n = { "<lang>": { "<field>": "<text>" } }, read via lib/i18n/localize.ts.

alter table courses add column i18n jsonb not null default '{}'::jsonb;
alter table course_modules add column i18n jsonb not null default '{}'::jsonb;
alter table lessons add column i18n jsonb not null default '{}'::jsonb;

-- Translations for the seed content (20260921000001_seed_courses.sql).
update courses set i18n = '{"en":{"title":"Path Animation Fundamentals","subtitle":"From frame to motion","description":"The first course: how the pipeline works and how to build a short study."},"de":{"title":"Grundlagen der Path-Animation","subtitle":"Vom Bild zur Bewegung","description":"Der erste Kurs: wie die Pipeline funktioniert und wie man eine kurze Studie erstellt."},"fr":{"title":"Les bases de l''animation Path","subtitle":"De l''image au mouvement","description":"Premier cours : comment fonctionne le pipeline et comment réaliser une courte étude."},"es":{"title":"Fundamentos de la animación Path","subtitle":"Del fotograma al movimiento","description":"El primer curso: cómo funciona el pipeline y cómo crear un estudio corto."},"it":{"title":"Fondamenti dell''animazione Path","subtitle":"Dal fotogramma al movimento","description":"Il primo corso: come funziona la pipeline e come realizzare un breve studio."},"zh":{"title":"路径动画基础","subtitle":"从画面到运动","description":"第一门课：制作流程如何运作，以及如何完成一个短小的练习作品。"},"ja":{"title":"パスアニメーションの基礎","subtitle":"フレームから動きへ","description":"最初のコース：パイプラインの仕組みと短い習作の作り方。"}}'::jsonb where id = 'a1000000-0000-0000-0000-000000000001';
update courses set i18n = '{"en":{"title":"Storytelling in the Frame","subtitle":"Scene, rhythm, character","description":"How to hold attention: scene structure and visual rhythm."},"de":{"title":"Storytelling im Bild","subtitle":"Szene, Rhythmus, Figur","description":"Aufmerksamkeit halten: Szenenstruktur und visueller Rhythmus."},"fr":{"title":"Raconter en images","subtitle":"Scène, rythme, personnage","description":"Capter l''attention : structure de scène et rythme visuel."},"es":{"title":"Narrativa en el plano","subtitle":"Escena, ritmo, personaje","description":"Cómo mantener la atención: estructura de escena y ritmo visual."},"it":{"title":"Storytelling nell''inquadratura","subtitle":"Scena, ritmo, personaggio","description":"Come mantenere l''attenzione: struttura della scena e ritmo visivo."},"zh":{"title":"镜头中的叙事","subtitle":"场景、节奏、角色","description":"如何抓住注意力：场景结构与视觉节奏。"},"ja":{"title":"フレームの中のストーリーテリング","subtitle":"シーン、リズム、キャラクター","description":"注意を引きつける方法：シーン構成と視覚的リズム。"}}'::jsonb where id = 'a1000000-0000-0000-0000-000000000002';
update courses set i18n = '{"en":{"title":"Production Pipeline","subtitle":"From asset to final build","description":"Roles, stages and the typical bottlenecks of production."},"de":{"title":"Produktionspipeline","subtitle":"Vom Asset zum fertigen Build","description":"Rollen, Phasen und typische Engpässe der Produktion."},"fr":{"title":"Pipeline de production","subtitle":"De l''asset au montage final","description":"Rôles, étapes et goulots d''étranglement typiques de la production."},"es":{"title":"Pipeline de producción","subtitle":"Del asset al montaje final","description":"Roles, etapas y cuellos de botella típicos de la producción."},"it":{"title":"Pipeline di produzione","subtitle":"Dall''asset al montaggio finale","description":"Ruoli, fasi e tipici colli di bottiglia della produzione."},"zh":{"title":"制作流程","subtitle":"从素材到成片","description":"制作中的角色、阶段和常见瓶颈。"},"ja":{"title":"制作パイプライン","subtitle":"アセットから完成まで","description":"制作における役割、工程、よくあるボトルネック。"}}'::jsonb where id = 'a1000000-0000-0000-0000-000000000003';
update courses set i18n = '{"en":{"title":"Sound and Editing","subtitle":"Hear the picture","description":"Editing basics, pacing and working with the soundtrack."},"de":{"title":"Ton und Schnitt","subtitle":"Das Bild hören","description":"Schnittgrundlagen, Tempo und Arbeit mit der Tonspur."},"fr":{"title":"Son et montage","subtitle":"Entendre l''image","description":"Bases du montage, rythme et travail sur la bande sonore."},"es":{"title":"Sonido y montaje","subtitle":"Escuchar la imagen","description":"Montaje básico, ritmo y trabajo con la pista de sonido."},"it":{"title":"Suono e montaggio","subtitle":"Ascoltare l''immagine","description":"Basi del montaggio, ritmo e lavoro con la traccia audio."},"zh":{"title":"声音与剪辑","subtitle":"听见画面","description":"剪辑基础、节奏以及音轨处理。"},"ja":{"title":"サウンドと編集","subtitle":"映像を聴く","description":"編集の基本、テンポ、サウンドトラックの扱い方。"}}'::jsonb where id = 'a1000000-0000-0000-0000-000000000004';
update courses set i18n = '{"en":{"title":"Releasing a Short Film","subtitle":"Show your work to the world","description":"Export, platforms and how to put together a demo reel."},"de":{"title":"Kurzfilm veröffentlichen","subtitle":"Zeig deine Arbeit der Welt","description":"Export, Plattformen und wie man ein Demoreel zusammenstellt."},"fr":{"title":"Sortir un court métrage","subtitle":"Montrer son travail au monde","description":"Export, plateformes et comment monter une bande démo."},"es":{"title":"Estreno de un cortometraje","subtitle":"Muestra tu trabajo al mundo","description":"Exportación, plataformas y cómo montar un demo reel."},"it":{"title":"Pubblicare un cortometraggio","subtitle":"Mostra il tuo lavoro al mondo","description":"Esportazione, piattaforme e come creare uno showreel."},"zh":{"title":"短片发布","subtitle":"向世界展示作品","description":"导出、发布平台以及如何制作作品集短片。"},"ja":{"title":"短編映画のリリース","subtitle":"作品を世界に届ける","description":"書き出し、公開先、デモリールのまとめ方。"}}'::jsonb where id = 'a1000000-0000-0000-0000-000000000005';
update course_modules set i18n = '{"en":{"title":"Getting started","description":"Why this course"},"de":{"title":"Start","description":"Warum dieser Kurs"},"fr":{"title":"Démarrage","description":"Pourquoi ce cours"},"es":{"title":"Inicio","description":"Por qué este curso"},"it":{"title":"Inizio","description":"Perché questo corso"},"zh":{"title":"开始","description":"为什么学这门课"},"ja":{"title":"スタート","description":"このコースを学ぶ理由"}}'::jsonb where id = 'b1000000-0000-0000-0000-000000000001';
update course_modules set i18n = '{"en":{"title":"Practice","description":"Your first study"},"de":{"title":"Praxis","description":"Deine erste Studie"},"fr":{"title":"Pratique","description":"Votre première étude"},"es":{"title":"Práctica","description":"Tu primer estudio"},"it":{"title":"Pratica","description":"Il tuo primo studio"},"zh":{"title":"实践","description":"你的第一个练习"},"ja":{"title":"実践","description":"最初の習作"}}'::jsonb where id = 'b1000000-0000-0000-0000-000000000002';
update course_modules set i18n = '{"en":{"title":"Scene"},"de":{"title":"Szene"},"fr":{"title":"Scène"},"es":{"title":"Escena"},"it":{"title":"Scena"},"zh":{"title":"场景"},"ja":{"title":"シーン"}}'::jsonb where id = 'b1000000-0000-0000-0000-000000000003';
update course_modules set i18n = '{"en":{"title":"Stages"},"de":{"title":"Phasen"},"fr":{"title":"Étapes"},"es":{"title":"Etapas"},"it":{"title":"Fasi"},"zh":{"title":"阶段"},"ja":{"title":"工程"}}'::jsonb where id = 'b1000000-0000-0000-0000-000000000004';
update course_modules set i18n = '{"en":{"title":"Editing"},"de":{"title":"Schnitt"},"fr":{"title":"Montage"},"es":{"title":"Montaje"},"it":{"title":"Montaggio"},"zh":{"title":"剪辑"},"ja":{"title":"編集"}}'::jsonb where id = 'b1000000-0000-0000-0000-000000000005';
update course_modules set i18n = '{"en":{"title":"Release"},"de":{"title":"Veröffentlichung"},"fr":{"title":"Sortie"},"es":{"title":"Estreno"},"it":{"title":"Pubblicazione"},"zh":{"title":"发布"},"ja":{"title":"リリース"}}'::jsonb where id = 'b1000000-0000-0000-0000-000000000006';
update lessons set i18n = '{"en":{"title":"Why learn from your own frames"},"de":{"title":"Warum mit eigenen Bildern lernen"},"fr":{"title":"Pourquoi apprendre sur vos propres images"},"es":{"title":"Por qué aprender con tus propios fotogramas"},"it":{"title":"Perché imparare dai propri fotogrammi"},"zh":{"title":"为什么用自己的画面学习"},"ja":{"title":"自分のフレームで学ぶ理由"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000001';
update lessons set i18n = '{"en":{"title":"Notes: pipeline glossary"},"de":{"title":"Notizen: Pipeline-Glossar"},"fr":{"title":"Fiche : glossaire du pipeline"},"es":{"title":"Apuntes: glosario del pipeline"},"it":{"title":"Appunti: glossario della pipeline"},"zh":{"title":"笔记：制作流程术语表"},"ja":{"title":"ノート：パイプライン用語集"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000002';
update lessons set i18n = '{"en":{"title":"A 10-second study"},"de":{"title":"Eine 10-Sekunden-Studie"},"fr":{"title":"Une étude de 10 secondes"},"es":{"title":"Un estudio de 10 segundos"},"it":{"title":"Uno studio di 10 secondi"},"zh":{"title":"10 秒练习"},"ja":{"title":"10秒の習作"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000003';
update lessons set i18n = '{"en":{"title":"Scene beats"},"de":{"title":"Szenen-Beats"},"fr":{"title":"Les temps forts d''une scène"},"es":{"title":"Beats de la escena"},"it":{"title":"I beat della scena"},"zh":{"title":"场景节拍"},"ja":{"title":"シーンのビート"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000004';
update lessons set i18n = '{"en":{"title":"Shot breakdown"},"de":{"title":"Einstellungsanalyse"},"fr":{"title":"Analyse d''un plan"},"es":{"title":"Análisis de un plano"},"it":{"title":"Analisi di un''inquadratura"},"zh":{"title":"镜头拆解"},"ja":{"title":"ショット分析"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000005';
update lessons set i18n = '{"en":{"title":"Stage map"},"de":{"title":"Phasenübersicht"},"fr":{"title":"Carte des étapes"},"es":{"title":"Mapa de etapas"},"it":{"title":"Mappa delle fasi"},"zh":{"title":"阶段地图"},"ja":{"title":"工程マップ"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000006';
update lessons set i18n = '{"en":{"title":"Handoffs between roles"},"de":{"title":"Übergaben zwischen Rollen"},"fr":{"title":"Transmission entre les rôles"},"es":{"title":"Traspasos entre roles"},"it":{"title":"Passaggi di consegne tra ruoli"},"zh":{"title":"角色之间的交接"},"ja":{"title":"役割間の引き継ぎ"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000007';
update lessons set i18n = '{"en":{"title":"Cutting pace"},"de":{"title":"Schnitttempo"},"fr":{"title":"Rythme des coupes"},"es":{"title":"Ritmo de corte"},"it":{"title":"Ritmo dei tagli"},"zh":{"title":"剪辑节奏"},"ja":{"title":"カットのテンポ"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000008';
update lessons set i18n = '{"en":{"title":"Mix notes"},"de":{"title":"Notizen zur Mischung"},"fr":{"title":"Notes de mixage"},"es":{"title":"Notas de mezcla"},"it":{"title":"Note sul mix"},"zh":{"title":"混音笔记"},"ja":{"title":"ミックスのメモ"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000009';
update lessons set i18n = '{"en":{"title":"Export and checklist"},"de":{"title":"Export und Checkliste"},"fr":{"title":"Export et check-list"},"es":{"title":"Exportación y checklist"},"it":{"title":"Esportazione e checklist"},"zh":{"title":"导出与检查清单"},"ja":{"title":"書き出しとチェックリスト"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000010';
update lessons set i18n = '{"en":{"title":"Voice-over for your reel"},"de":{"title":"Voice-over für dein Reel"},"fr":{"title":"Voix off pour votre bande démo"},"es":{"title":"Voz en off para tu reel"},"it":{"title":"Voce fuori campo per lo showreel"},"zh":{"title":"作品集旁白"},"ja":{"title":"リール用ナレーション"}}'::jsonb where id = 'c1000000-0000-0000-0000-000000000011';
